apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: raghav-node-app:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGODB_URL
              value: "mongodb://mongodb-service:27017/mydb"
            - name: SESSION_SECRET
              value: "your_secure_secret_key_here"
            - name: SESSION_KEY_NAME
              value: "flashMessage"